runtime: nodejs18

env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/etown-questions-queue:us-central1:etown-qq
  DB_USER: root
  DB_PASS: etown-qq
  DB_NAME: etownqq
  

handlers:
- url: /.*
  static_dir: /static/.*