runtime: nodejs18

env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/etown-code-green:uscentral1:code-green
  DB_USER: root
  DB_PASS: etown-code-green
  DB_NAME: etowncodeGreen
  

handlers:
- url: /.*
  static_dir: /static/.*